baseURL: "https://www.yaotian-huang.com"
languageCode: "en-us"
title: "Tim (Yaotian) Huang"
theme: "charlolamode"

enableInlineShortcodes: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

menu:
  main:
    - name: Projects
      url: games/
      weight: 1
    - name: DevLog
      url: devlog/
      weight: 2
    - name: Tutorial
      url: tutorial/
      weight: 3
    # - name: University
    #   url: uni/
    #   weight: 4
    #  weight: 10

params:
    author: sky-haihai


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Tim (Yaotian) Huang
        description: |
          Technical(70%) Artist(29%)
        imageUrl: "/images/profile.png"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: My Projects
              url: /games/
            - name: DevLog
              url: /devlog/
    mainSections:
      - posts

    socialIcons:
        - name: github
          url: "https://github.com/sky-haihai"
        - name: linkedin
          url: "https://www.linkedin.com/in/yaotian-huang/"
        - name: twitter
          url: "https://www.twitter.com/yaotianh"
        - name: instagram
          url: "https://www.instagram.com/sky_haihai/"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

taxonomies:
  category: categories
  tag: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

markup:
  goldmark:
    renderer:
      unsafe: true
