baseURL: "https://www.yaotian-huang.com"
title: "Portfolio"
paginate: 50
theme: "charlolamode"



menu:
  main:
    - name: Projects
      url: projects/
      weight: 1
    - name: TA
      url: ta/
      weight: 2
    - name: Code
      url: code/
      weight: 3
    - name: Art
      url: art/
      weight: 4
    # - name: University
    #   url: uni/
    #   weight: 4
    #  weight: 10



params:
    author: Tim Huang


    defaultTheme: auto
    dateFormat: "Jan 2, 2006"
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Tim (Yaotian) Huang
        description: |
          Technical(70%) Artist(29%)
        imageUrl: "/images/profile.png"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Projects
              url: projects/
            - name: TA
              url: ta/
            - name: Code
              url: code/
            - name: Art
              url: art/
    mainSections:
      - project

    socialIcons:
        - name: github
          url: "https://github.com/sky-haihai"
        - name: linkedin
          url: "https://www.linkedin.com/in/yaotian-huang/"
        - name: twitter
          url: "https://www.twitter.com/yaotianh"
        - name: instagram
          url: "https://www.instagram.com/sky_haihai/"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
      favicon: "/images/favicon64.ico"
      favicon16x16: "/images/favicon16.png"
      favicon32x32: "/images/favicon32.png"
      apple_touch_icon: "/images/favicon128.png"
      safari_pinned_tab: "/images/favicon128.png"


enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

markup:
  goldmark:
    renderer: 
      unsafe: true


defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  jp:
    contentDir: content/jp
    languageCode: ja
    languageName: JP
    params:
      reading_speed: 175
    weight: 2
    title: "ポートフォリオ"
    menu:
      main:
        - name: プロジェクト
          url: projects/
          weight: 1
        - name: テクニカルアート
          url: ta/
          weight: 2
        - name: プログラミング
          url: code/
          weight: 3
        - name: アート
          url: art/
          weight: 4
    params:
      author: 黃 堯天
      profileMode:
        title: 黃 堯天
        description: |
          Technical(70%) Artist(29%)
        imageUrl: "/images/profile.png"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: プロジェクト
              url: projects/
            - name: テクニカルアート
              url: ta/
            - name: プログラミング
              url: code/
            - name: アート
              url: art/
      mainSections:
        - プロジェクト

      socialIcons:
          - name: github
            url: "https://github.com/sky-haihai"
          - name: linkedin
            url: "https://www.linkedin.com/in/yaotian-huang/"
          - name: twitter
            url: "https://www.twitter.com/yaotianh"
          - name: instagram
            url: "https://www.instagram.com/sky_haihai/"
  en:
    contentDir: content/en
    languageCode: en-US
    languageName: EN
    params:
      reading_speed: 175
    weight: 1

  cn:
    contentDir: content/cn
    languageCode: zh-cn
    languageName: CN
    params:
      reading_speed: 175
    weight: 3
    title: "作品集"
    menu:
      main:
        - name: 项目作品
          url: projects/
          weight: 1
        - name: 技术美术
          url: ta/
          weight: 2
        - name: 程序
          url: code/
          weight: 3
        - name: 美术
          url: art/
          weight: 4
    params:
      author: 黄尧天
      profileMode:
        title: 黄尧天
        description: |
          Technical(70%) Artist(29%)
        imageUrl: "/images/profile.png"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: 项目作品
              url: projects/
            - name: 技术美术
              url: ta/
            - name: 程序
              url: code/
            - name: 美术
              url: art/
      mainSections:
        - 项目作品